title: Meteor Vue3 Tutorial
subtitle: Vue3 Tutorial
versions:
  - '1'
versioned-netlify-redirects:
  netlify_site_id: meteor-vue-tutorial
sidebar_categories:
  null:
    - index
    - changelog
  Simple Todos:
    - simple-todos/index
    - simple-todos/01-creating-app
    - simple-todos/02-collections
    - simple-todos/03-forms-and-events
    - simple-todos/04-update-and-remove
    - simple-todos/05-styles
    - simple-todos/06-filter-tasks
    - simple-todos/07-adding-user-accounts
    - simple-todos/08-running-on-mobile
    - simple-todos/09-testing
    - simple-todos/10-deploying
    - simple-todos/11-next-steps
github_repo: 'meteor/vue3-tutorial'

url: https://vue3-tutorial.meteor.com/
root: /

source_dir: tutorial
content_root: tutorial

highlight:
  enable: false

logo:
  title:
  subtitle: Vue3 Tutorial
